# Generated by Django 3.0.8 on 2020-09-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='list_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]

