# Generated by Django 3.0.8 on 2020-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200910_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='list_id',
            field=models.IntegerField(),
        ),
    ]

