# Generated by Django 3.0.8 on 2020-09-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200910_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]

